# Generated by Django 2.0.4 on 2018-05-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='назва банку')),
                ('mfo', models.PositiveIntegerField(max_length=6, verbose_name='мфо')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='повна назва підприємства')),
                ('short_name', models.CharField(max_length=80, verbose_name='скорочена назва підприєства')),
                ('inn', models.CharField(blank=True, max_length=15, verbose_name='ідентификаційний номер')),
                ('edrpoy', models.CharField(blank=True, max_length=10, verbose_name='єдрпоу')),
                ('dfro', models.CharField(blank=True, max_length=15, verbose_name='дфро')),
                ('payment_account', models.CharField(blank=True, max_length=20, verbose_name='розрахунковий рахунок')),
                ('cert_vat', models.CharField(blank=True, max_length=15, verbose_name='свідоцтво платника пдв')),
                ('dir_name', models.CharField(blank=True, max_length=150, verbose_name='директор')),
                ('responsible', models.CharField(blank=True, max_length=150, verbose_name='відповідальна особа')),
                ('phone1', models.CharField(blank=True, max_length=16, verbose_name='номер телефона')),
                ('phone2', models.CharField(blank=True, max_length=16, verbose_name='номер телефона')),
                ('phone3', models.CharField(blank=True, max_length=16, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
                ('zipcode', models.PositiveIntegerField(default=0, max_length=6, verbose_name='поштовий індекс')),
                ('country', models.CharField(default='Україна', max_length=20, verbose_name='країна')),
                ('region', models.CharField(default='Волинська обл.', max_length=50, verbose_name='область')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='район')),
                ('town', models.CharField(blank=True, max_length=50, verbose_name='населений пункт')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='адреса')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.Bank')),
            ],
        ),
    ]
