# Generated by Django 2.0.4 on 2018-05-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20180501_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='mfo',
            field=models.PositiveIntegerField(verbose_name='мфо'),
        ),
    ]
