# Generated by Django 2.0.4 on 2018-05-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_auto_20180501_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='entity',
            field=models.BooleanField(default=False, verbose_name='юридична особа'),
        ),
    ]
