# Generated by Django 2.0.4 on 2018-05-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_partner_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='mfo',
            field=models.PositiveIntegerField(unique=True, verbose_name='мфо'),
        ),
    ]
