# Generated by Django 2.0.4 on 2018-05-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_auto_20180503_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crmapp.Bank', verbose_name='банк'),
        ),
    ]
