# Generated by Django 2.0.4 on 2018-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='послуга/робота'),
        ),
    ]
