# Generated by Django 2.0.4 on 2018-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_auto_20180518_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='phone1',
            field=models.CharField(blank=True, max_length=16, verbose_name='номер телефона'),
        ),
    ]
