# Generated by Django 2.0.4 on 2018-05-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_auto_20180518_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_invoice', models.PositiveIntegerField(unique=True, verbose_name='№ рахунку')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('works', models.TextField(blank=True, verbose_name='назва')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ціна')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='crmapp.Contract', verbose_name='договір')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer', to='crmapp.Partner', verbose_name='платник')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performer', to='crmapp.Firm', verbose_name='виконавець')),
            ],
        ),
    ]
