# Generated by Django 2.0.4 on 2018-05-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.PositiveIntegerField(verbose_name='№ договору'),
        ),
    ]
