# Generated by Django 2.0.4 on 2018-05-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_auto_20180523_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='crmapp.Contract', verbose_name='договір'),
        ),
    ]
