# Generated by Django 2.0.4 on 2018-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_auto_20180523_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='num_invoice',
            field=models.PositiveIntegerField(blank=True, verbose_name='№ рахунку'),
        ),
    ]
