# Generated by Django 2.0.4 on 2018-05-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_invoice_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paid',
            new_name='is_paid',
        ),
    ]
