# Generated by Django 2.0.4 on 2018-05-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_auto_20180526_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateField(verbose_name='дата'),
        ),
    ]
