# Generated by Django 2.0.4 on 2018-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_auto_20180526_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cost_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='вартість з ПДВ'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ПДВ'),
        ),
    ]
