# Generated by Django 2.0.4 on 2018-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_auto_20180528_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ціна з ПДВ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ПДВ'),
        ),
    ]
