# Generated by Django 2.0.4 on 2018-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0020_auto_20180531_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateField(default='2018-05-31', verbose_name='дата'),
        ),
    ]
