# Generated by Django 2.0.4 on 2018-06-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0021_auto_20180531_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_act', models.PositiveIntegerField(verbose_name='№ акту')),
                ('date_create', models.DateField(default='2018-06-01', verbose_name='дата')),
                ('agent_firm', models.CharField(max_length=150, verbose_name='представник виконвця')),
                ('agent_client', models.CharField(max_length=150, verbose_name='представник замовника')),
                ('works', models.TextField(blank=True, verbose_name='назва робіти, послуг')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ціна')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ПДВ')),
                ('price_vat', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, verbose_name='ціна з ПДВ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_partner', to='crmapp.Partner', verbose_name='замовник')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_contract', to='crmapp.Contract', verbose_name='договір')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_performer', to='crmapp.Firm', verbose_name='виконавець')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateField(default='2018-06-01', verbose_name='дата'),
        ),
    ]
