# Generated by Django 2.0.4 on 2018-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_auto_20180601_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='agent_firm',
            field=models.CharField(max_length=150, verbose_name='представник виконавця'),
        ),
    ]
