# Generated by Django 2.0.4 on 2018-06-03 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmapp', '0023_auto_20180601_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='назва проекту')),
                ('date_create', models.DateField(default='2018-06-03', verbose_name='дата створення')),
                ('date_end', models.DateField(verbose_name='дата виконання')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='змінено')),
                ('status', models.SmallIntegerField(default='0', verbose_name='прогрес')),
                ('is_finished', models.BooleanField(verbose_name='завершено')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='crmapp.Contract', verbose_name='договір')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default='2018-06-03', verbose_name='дата створення')),
                ('date_end', models.DateField(verbose_name='дата виконання')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='змінено')),
                ('status', models.CharField(blank=True, choices=[(None, 'Нове'), ('underway', 'Виконується'), ('done', 'Завершено')], max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_in_project', to='crmapp.Project', verbose_name='проект')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Services')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to=settings.AUTH_USER_MODEL, verbose_name='виконавець')),
            ],
        ),
        migrations.AlterField(
            model_name='act',
            name='date_create',
            field=models.DateField(default='2018-06-03', verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_create',
            field=models.DateField(default='2018-06-03', verbose_name='дата'),
        ),
    ]
