# Generated by Django 2.0.4 on 2018-06-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0026_auto_20180605_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crmapp.Services', verbose_name='роботи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Нове'), ('underway', 'Виконується'), ('done', 'Завершено')], max_length=15, verbose_name='статус'),
        ),
    ]
